services:
  tg_password_manager:
    build: .
    command: ["python", "app/main.py"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    restart: "unless-stopped"
    env_file: .env
    volumes:
      - ./scrypt/:/docker-entrypoint-initdb.d/


    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
